name: DOCKER
on: 
  workflow_dispatch:
jobs:
  deploy:
    concurrency:
      group: deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: badri.vaikunth@gmail.com
        password: Srihari@2025
    - name: Nginx Creation
      run: docker run --name my-nginx -p 8080:80 -d nginx
    - name: Running Containers
      timeout-minutes: 1
      run: |
        docker ps -a
        sleep 100s
