name: DOCKER
on: 
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: badri.vaikunth@gmail.com
        password: Srihari@2025
    - name: Nginx Creation
      run: docker run --name my-nginx -p 8080:80 -d nginx
    - name: Running Containers
      run: docker ps -a
